// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  // State of the database
  schema: 'prisma/schema.prisma',
  // Updates on the database
  migrations: {
    path: 'prisma/migrations',
  },
  // The place where the data lives
  datasource: {
    url: env('DATABASE_URL'),
  },
});
